### ISSUE TITLE
Cannot determine entity kind of reference

### ISSUE THREAD

**Issue by nsherry4** [objectof-group/objectof#3]
Consider a simple Schema:

### Person
 *  job : Reference to Job

### Job

When working with the generic data structures (ie without any generated Java beans) it is impossible to determine which entity kind Person.job is referencing, as the Kind returned for it describes the reference, rather than the reference target.

**Comment by nsherry4** [comment]
Okay, so I can see a couple ways of fixing this:

Properties
------------
It doesn't look like properties are preserved in the database/repository right now. If they were, the target kind could be retrieved with:
```java
Property href = kind.getProperty("ans://objectof.net:1401/facets/model/href");
Kind<?> target = package.forName(href.getUniqueName());
```


Parts
---------------
If we added a `target` field to the `types` table like below, we could have the `getParts` call return the target kind.

```sql
create table types
(
  id smallint not null,
  repository bigint not null,
  path text not null,
  stereotype text not null,
  target smallint,
  constraint types_pk 
  primary key (id)
  foreign key (target) references types(id)
);
```

**Comment by jdhaley** [comment]
The idea was that the reference was but one piece of type data that could be attached to a type and all of that info would be contained in the schema repo (which i believe is attached via the repositories table(???).  Possibly the schema repo isn't created (I can't remember now).  The goal was to link a repo with the schema repo.

So... I recommend:
(1) Look a bit into what I'm mentioned regarding the schema repo.  If there's anything there we can consider that approach.

(2) If that doesn't pan out we can be pragmatic and add the target into into the types (or just do it anyway as a 'de-normalization'... it's kind of a central concept anyway).

**Comment by jdhaley** [comment]
Further review...
- I believe you also need a target_repository (bigint) field because the type id is only unique within the repo I imagine.
- Note that the code must support a repo (via repository) that doesn't actually exist in the current database - although its types will.  The repo table should have a column indicating the database/stub in which the entity can be found.
* More about the above point... 
  * an entity reference should be considered 'soft'.  It can exist anywhere.  Ideally, the referencing repo has info. to get it or redirect there.
  * 'external' repos are stubs to the real repo...
    * We can even cache a subset of entity properties from the external repo when we get it.  This allows us to send some key properties to define a 'handle' to an external entity when the entity is coming from this repo/database.  For example, a 'caption' property so that a ui can show an icon (via the type) and a caption much like an OS displays lists of files.
     * The client code can then asynchronously call out to the actual repo to fetch all the data when needed.  In the case where a referenced entity is only a cache/stub there should be some visual clue to the user that the data may be 'out of date'
  * parts can't be referenced in general.  Think of them as an element of a xml document.

**Comment by nsherry4** [comment]
I'm going to split this up into two issues.
* Keeping a record of reference targets
* Reference targets being able to point across repos/databases (#5)

I've resolved the former issue by adding a target field to the types table (turns out the id is unique across all repositories in a database) and by having reference kinds track their target type in the parts list. 

There doesn't appear to be any schema repo created by default, and a quick look didn't turn up any existing code which was being skipped accidentally.

I'm going to create a new issue for the second part, copy your comments into it, and mark this as closed.
