### ISSUE TITLE
Add support for MEDIA stereotype

### ISSUE THREAD

**Issue by nsherry4** [objectof-group/objectof#4]
IBaseMetamodel maps the MEDIA stereotype to an IUnsupportedDatatype, which presents the value as Boolean.

**Comment by nsherry4** [comment]
John, will we need to add a 'blobs' table to repositories similar to the 'chars' table?

**Comment by jdhaley** [comment]
Exactly.
Both chars & blobs may want a full text index on them.  For the blobs only index those media types that contain character data (such as a word document).  Keep in mind a normal text file should just be a chars file... this includes json, xml, or anything held in text.

**Comment by nsherry4** [comment]
> Both chars & blobs may want a full text index on them. For the blobs only index those media types that contain character data (such as a word document).

Do you mean that we should only compute the hash for entries which contain character data? How should we detect this -- do you want a media/mimetype field, or do you want to try and detect which data is character data?

> Keep in mind a normal text file should just be a chars file... this includes json, xml, or anything held in text.

I'm not sure what you mean by a "chars file". Do you mean that you want to store it in the chars table?

**Comment by nsherry4** [comment]
I've implemented rudimentary blob support, but currently there is no indexing. It is currently using the same approach as the chars table for storing byte strings. This could become an issue, though, as blobs will probably be larger on average than strings, and less likely to collide, and currently there is no way to "clean out" the blobs table.

Assigning this to you again for feedback.

**Comment by jdhaley** [comment]
Let's create an enhancement issue for identifying de-referenced elements, blobs, and chars.  I would like it to be 2-phased:
- A background daemon to identify de-referenced elements.   This is run BEFORE a backup or export is done. Elements should just be logically deleted (moved to the transaction/audit table like an explicit delete).  Chars and blobs should just have an row attribute set.  SQL will need to change to filter these out (so we don't revive deleted objects into zombies).
- A process to purge these objects.  This process can be (optionally) scheduled to run AFTER a backup or export is done or run manually or run when disk usage is beyond a given threshold.
